repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        name: Black
        args: [-S]
        language_version: python3.7

  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        entry: flake8 --config=.flake8 --format
        language: python

  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
