language: python
python:
  - 3.8
services:
  postgresql
addons:
  postgresql: '10'
env:
  global:
    - PIPENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install -q pipenv
  - pipenv sync -d
  - cp contrib/env_sample .env
before_script:
  - psql -c "CREATE DATABASE testedb;" -U postgres
script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro
after_success:
  - pipenv run codecov
