version: "3.8"

services:
  database:
    container_name: pythonprodjango
    image: postgres:11
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pyprodb
    ports:
      - 5434:5432

volumes:
  dbdata:
