# Generated by Django 3.0.8 on 2020-07-19 23:02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(old_name='Modulos', new_name='Modulo',),
    ]
