# Generated by Django 3.0.8 on 2020-07-31 03:19
from django.db import migrations
from django.utils.text import slugify


def popular_slug(apps, schema_editor):
    Modulo = apps.get_model('modulos', 'Modulo')
    for modulo in Modulo.objects.all():
        modulo.slug = slugify(modulo.titulo)
        modulo.save()


class Migration(migrations.Migration):
    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [migrations.RunPython(popular_slug)]
