# Generated by Django 3.1.1 on 2020-09-19 00:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_aula'),
    ]

    operations = [
        migrations.AddField(model_name='aula', name='vimeo_id', field=models.CharField(default='1', max_length=32),),
    ]
