# Generated by Django 3.1.1 on 2020-09-19 00:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_aula_vimeo_id'),
    ]

    operations = [
        migrations.AlterField(model_name='aula', name='vimeo_id', field=models.CharField(max_length=32),),
    ]
