# Generated by Django 3.0.8 on 2020-07-19 23:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('aperitivos', '0002_video_creation'),
    ]

    operations = [
        migrations.AlterField(model_name='video', name='slug', field=models.SlugField(max_length=32),),
    ]
