name: CI

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Copying configurations
      run: |
        cp contrib/env_sample .env
    - name: Install Dependencies
      run: |
        pip install pipenv
        pipenv sync -d
    - name: Lynt with Flake8
      run: |
        pipenv run flake8 --config=.flake8
    - name: Tests with Pytest
      run: |
        pipenv run pytest pypro --cov=pypro
    - name: Posting Coverage
      env:
        CODECOV_TOKEN: "81bd6bad-4b8a-4cc5-b558-1acba6bea06a"
      run: |
        pipenv run codecov
